version: '3.3'
services:
  invalidation_lambda:
    build:
      context: ./cloudfront/invalidation/lambda
  iiif_edge_lambdas:
    build:
      context: ./cloudfront/iiif.wellcomecollection.org/edge-lambda
  iiif_tests:
    build:
      context: ./cloudfront/iiif.wellcomecollection.org/tests
  catalogue_tests:
    build:
      context: ./cloudfront/api.wellcomecollection.org/tests
