FROM amazon/aws-for-fluent-bit:latest

LABEL maintainer "Wellcome Collection <wellcomedigitalplatform@wellcome.org>"
LABEL description "Sends logs from platform applications to Elasticsearch"

ADD extra.conf /extra.conf
