steps:
  - label: "Wellcome Library STAGE Redirects"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: wellcome_library_edge_lambdas
          command: ["yarn", "testRedirectsStage"]

  - label: "Wellcome Library PROD Redirects"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: wellcome_library_edge_lambdas
          command: ["yarn", "testRedirects"]