steps:
  - command: .buildkite/scripts/run_autoformat.py
    label: "autoformat"

  - label: "test iiif_edge_lambdas"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: iiif_edge_lambdas
          command: ["yarn", "test"]

  - label: "test wellcome_library_edge_lambdas"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: wellcome_library_edge_lambdas
          command: ["yarn", "test"]

  - label: "deploy iiif_edge_lambdas"
    branches: "master"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: iiif_edge_lambdas
          command: [ "yarn", "deploy" ]

  - label: "deploy wellcome_library_edge_lambdas"
    branches: "master"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: wellcome_library_edge_lambdas
          command: [ "yarn", "deploy" ]
