steps:
  - command: .buildkite/scripts/run_autoformat.py
    label: "autoformat"

  - wait

  - label: "test invalidation lambda"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: invalidation_lambda
          command: ["yarn", "test"]

  - label: "test iiif_edge_lambdas"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: iiif_edge_lambdas
          command: ["yarn", "test"]

  - wait

  - label: "deploy invalidation lambda"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: invalidation_lambda
          command: ["yarn", "deploy"]

  - label: "deploy iiif_edge_lambdas"
    branches: "main"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: iiif_edge_lambdas
          command: [ "yarn", "deploy" ]
