steps:
  - label: "Triggering platform-infrastructure-redirects on redirects branch name"
    trigger: "platform-infrastructure-redirects"
    branches: "redirects/*"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
  - label: "Triggering platform-infrastructure-redirects via git diff on cloudfront dir"
    branches: "!redirects/*"
    plugins:
      - chronotc/monorepo-diff#v1.3.0:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "cloudfront"
              config:
                label: "Trigger platform-infrastructure-redirects"
                trigger: "platform-infrastructure-redirects"
                build:
                  message: "${BUILDKITE_MESSAGE}"
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
                    BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
                    BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
